# Overwrite the bins created from the Spring Framework 5.* - When you try to register bins with the same name - BeanDefinitionOverrideException occurs, setting that eliminates this.
spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: never   # ANSI 색상 끄기    

logging:
  level:
    '[org.egovframe]': DEBUG
    '[egovframework]': DEBUG
    '[org.springframework]': DEBUG
#    root: DEBUG

