-- stgEmplyrCountStep 관련 배치 메타데이터 정리 스크립트
--
-- 1. 대상 JOB_EXECUTION_ID를 임시 테이블에 저장
CREATE TEMPORARY TABLE TMP_JOB_IDS
SELECT DISTINCT JOB_EXECUTION_ID
FROM BATCH_STEP_EXECUTION
WHERE STEP_NAME = 'stgEmplyrCountStep';

-- 2. Step 실행 상태를 FAILED로 변경
UPDATE BATCH_STEP_EXECUTION
SET STATUS = 'FAILED',
    EXIT_CODE = 'FAILED',
    EXIT_MESSAGE = CONCAT(IFNULL(EXIT_MESSAGE, ''), ' (cleanup-batch-meta.sql 실행)'),
    LAST_UPDATED = NOW()
WHERE STEP_NAME = 'stgEmplyrCountStep';

-- 3. Job 실행 상태를 FAILED로 변경
UPDATE BATCH_JOB_EXECUTION
SET STATUS = 'FAILED',
    EXIT_CODE = 'FAILED',
    EXIT_MESSAGE = CONCAT(IFNULL(EXIT_MESSAGE, ''), ' (cleanup-batch-meta.sql 실행)'),
    LAST_UPDATED = NOW()
WHERE JOB_EXECUTION_ID IN (SELECT JOB_EXECUTION_ID FROM TMP_JOB_IDS);

-- 4. Step 메타데이터 삭제
DELETE FROM BATCH_STEP_EXECUTION
WHERE STEP_NAME = 'stgEmplyrCountStep';

-- 5. Job 메타데이터 삭제
DELETE FROM BATCH_JOB_EXECUTION
WHERE JOB_EXECUTION_ID IN (SELECT JOB_EXECUTION_ID FROM TMP_JOB_IDS);

-- 6. 임시 테이블 제거
DROP TEMPORARY TABLE TMP_JOB_IDS;
