spring:
  profiles:
    active: local
  datasource:
    # 로컬 개발용 MySQL
    egovlocal-mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/egovlocal?useSSL=false&serverTimezone=UTC
      username: localuser
      password: localpass

    # 스테이징 MySQL (주 데이터베이스)
    migstg-mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/migstg?useSSL=false&serverTimezone=UTC
      username: miguser
      password: mig!1234

    # 원격1 CUBRID
    egovremote1-cubrid:
      driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
      url: "jdbc:cubrid:192.168.0.10:33000:egovremote1:::"
      username: readuser
      password: read!1234

erp:
  # ERP 시스템 API URL
  api-url: http://localhost:8080/api/erp
