-- 깨끗이 시작
DROP TABLE IF EXISTS comtnemplyrinfo;
DROP TABLE IF EXISTS comtnorgnztinfo;
DROP TABLE IF EXISTS erp_vehicle;

-- 조직 테이블
CREATE TABLE `comtnorgnztinfo` (
  `ORGNZT_ID` char(20) NOT NULL DEFAULT '' COMMENT '조직ID',
  `ORGNZT_NM` varchar(20) NOT NULL COMMENT '조직명',
  `ORGNZT_DC` varchar(100) DEFAULT NULL COMMENT '조직설명',
  PRIMARY KEY (`ORGNZT_ID`),
  UNIQUE KEY `COMTNORGNZTINFO_PK` (`ORGNZT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='조직정보';

-- 직원 테이블
CREATE TABLE `comtnemplyrinfo` (
  `EMPLYR_ID` varchar(20) NOT NULL COMMENT '업무사용자ID',
  `ORGNZT_ID` char(20) DEFAULT NULL COMMENT '조직ID',
  `USER_NM` varchar(60) NOT NULL COMMENT '사용자명',
  `SEXDSTN_CODE` char(1) DEFAULT NULL COMMENT '성별코드',
  `BRTHDY` char(20) DEFAULT NULL COMMENT '생일',
  `MBTLNUM` varchar(20) DEFAULT NULL COMMENT '이동전화번호',
  `EMAIL_ADRES` varchar(50) DEFAULT NULL COMMENT '이메일주소',
  `OFCPS_NM` varchar(60) DEFAULT NULL COMMENT '직위명',
  `EMPLYR_STTUS_CODE` char(1) DEFAULT NULL COMMENT '사용자상태코드',
  `REG_DTTM` datetime DEFAULT NULL COMMENT '등록일자',
  `MOD_DTTM` datetime DEFAULT NULL COMMENT '수정일자',
  PRIMARY KEY (`EMPLYR_ID`),
  UNIQUE KEY `COMTNEMPLYRINFO_PK` (`EMPLYR_ID`),
  KEY `COMTNEMPLYRINFO_i01` (`ORGNZT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='업무사용자정보';

-- ERP 차량 테이블
CREATE TABLE `erp_vehicle` (
  `VEHICLE_ID` varchar(20) NOT NULL COMMENT '차량ID',
  `MODEL` varchar(100) NOT NULL COMMENT '차량모델',
  `MANUFACTURER` varchar(100) NOT NULL COMMENT '제조사',
  `PRICE` decimal(15,2) DEFAULT NULL COMMENT '가격',
  `REG_DTTM` datetime NOT NULL COMMENT '등록일시',
  `MOD_DTTM` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`VEHICLE_ID`),
  UNIQUE KEY `ERP_VEHICLE_PK` (`VEHICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP 차량 정보';
