-- 깨끗이 시작
DROP TABLE IF EXISTS comtnemplyrinfo;
DROP TABLE IF EXISTS comtnorgnztinfo;
DROP TABLE IF EXISTS crm_customer;

-- 조직 테이블
CREATE TABLE `comtnorgnztinfo` (
  `ORGNZT_ID` char(20) NOT NULL DEFAULT '' COMMENT '조직ID',
  `ORGNZT_NM` varchar(20) NOT NULL COMMENT '조직명',
  `ORGNZT_DC` varchar(100) DEFAULT NULL COMMENT '조직설명',
  PRIMARY KEY (`ORGNZT_ID`),
  UNIQUE KEY `COMTNORGNZTINFO_PK` (`ORGNZT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='조직정보';

-- 직원 테이블
CREATE TABLE `comtnemplyrinfo` (
  `ESNTL_ID` varchar(20) NOT NULL COMMENT '고유ID',
  `EMPLYR_ID` varchar(20) NOT NULL COMMENT '업무사용자ID',
  `ORGNZT_ID` char(20) DEFAULT NULL COMMENT '조직ID',
  `USER_NM` varchar(60) NOT NULL COMMENT '사용자명',
  `SEXDSTN_CODE` char(1) DEFAULT NULL COMMENT '성별코드',
  `BRTHDY` char(20) DEFAULT NULL COMMENT '생일',
  `MBTLNUM` varchar(20) DEFAULT NULL COMMENT '이동전화번호',
  `EMAIL_ADRES` varchar(50) DEFAULT NULL COMMENT '이메일주소',
  `OFCPS_NM` varchar(60) DEFAULT NULL COMMENT '직위명',
  `EMPLYR_STTUS_CODE` char(1) DEFAULT NULL COMMENT '사용자상태코드',
  `REG_DTTM` datetime DEFAULT NULL COMMENT '등록일자',
  `MOD_DTTM` datetime DEFAULT NULL COMMENT '수정일자',
  PRIMARY KEY (`ESNTL_ID`),
  UNIQUE KEY `COMTNEMPLYRINFO_PK` (`ESNTL_ID`),
  KEY `COMTNEMPLYRINFO_i01` (`ORGNZT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='업무사용자정보';

-- CRM 고객 테이블
CREATE TABLE `crm_customer` (
  `CUSTOMER_ID` varchar(20) NOT NULL COMMENT '고객ID',
  `NAME` varchar(100) NOT NULL COMMENT '고객명',
  `EMAIL` varchar(100) DEFAULT NULL COMMENT '이메일',
  `PHONE` varchar(20) DEFAULT NULL COMMENT '전화번호',
  `REG_DTTM` datetime NOT NULL COMMENT '등록일시',
  `MOD_DTTM` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CUSTOMER_ID`),
  UNIQUE KEY `CRM_CUSTOMER_PK` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='CRM 고객 정보';
